ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 125
MONEY = 750
TOTAL_LEVELS = 15

#enemy constants
SPAWN_COOLDOWN = 400

#turret constants
TURRET_LEVELS = 4
BUY_COST = 200

UPGRADE_COST = 999



#HER KAN DERE ENDRE PÅ HVOR MYE DET SKAL KOSTE Å OPPGRADERE TURRETSENE TIL NIVÅ 2#
STABBER_UPGRADE_COST = 350
SHOOTER_UPGRADE_COST = 250
PANCAKE_UPGRADE_COST = 200





KILL_REWARD = 1
LEVEL_COMPLETE_REWARD = 225
ANIMATION_STEPS = 8
ANIMATION_STEPS_STABBER2 = 4
ANIMATION_STEPS_SHOOTER2 = 5
ANIMATION_STEPS_PANCAKE2 = 3
ANIMATION_DELAY = 15
DAMAGE = 5


MAX_TOTAL_TURRETS = 10

MAX_SHOOTERS = 2

MAX_STABBERS = 2

MAX_PANCAKES = 2